spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Users
  application:
    name: USER-SERVICE
  # File size limit for multipart requests
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
